### ISSUE TITLE
SRS:Introduction

### ISSUE THREAD

**Issue by zhbancheva** [janito84/naturalmilk#1]
For SRS to create part **Introduction** 
To cover the following points: purpose, scope, overview etc.

For example file _QA-FundamentalsSRS-Example-Team_Provers_v2_ points or other files.

**Comment by softunigroupproject** [comment]
I've started the task and so far I am not coming up with any issues. I will notify you when I am done. 
Here is the raw version of the doc. 
https://docs.google.com/document/d/1CEaR4QuqgcsreeBnnenLGa0oT6Zg9xLiXOOVhjd_fBw/edit#

**Comment by softunigroupproject** [comment]
[Software Requirements Specification Petra NOT done.docx](https://github.com/janito84/naturalmilk/files/223705/Software.Requirements.Specification.Petra.NOT.done.docx)

**Comment by softunigroupproject** [comment]
This task has been completed successfully. 
https://docs.google.com/document/d/1CEaR4QuqgcsreeBnnenLGa0oT6Zg9xLiXOOVhjd_fBw/edit#heading=h.hhotu2pqwobx

I will be managing the document in google docs to make sure all parts are written by the team.
