### ISSUE TITLE
SRS: Data Flow Diagrams (DFD)

### ISSUE THREAD

**Issue by softunigroupproject** [janito84/naturalmilk#10]
Creating a DFD in the SRS is necessary in order for us to be able to avoid ambiguousness in our project.

**Comment by DessLazaro** [comment]
SRS with some format changes is available in Google docs https://docs.google.com/document/d/1CEaR4QuqgcsreeBnnenLGa0oT6Zg9xLiXOOVhjd_fBw/edit#heading=h.hhotu2pqwobx
