### ISSUE TITLE
Non-functional requirements

### ISSUE THREAD

**Issue by DessLazaro** [janito84/naturalmilk#12]
i.e. should cover the following topics:
1. Usability;
2. Performance;
3. Security;
4. Interfaces;
5. Legal.

@bobosam @janito84 Is there anything else we need to include here? Please also see the attached draft file.

**Comment by zhbancheva** [comment]
Dessi, I think this is enough only this part _"The customer’s web browser shall never display a customer’s credit card number after retrieving from the database.  It shall always be shown with just the last 4 digits of the credit card number."_ is not true, beacause the system don't use credit card for shopping, only cash on delivery.

**Comment by DessLazaro** [comment]
Final file version uploaded.
