### ISSUE TITLE
Test plan: Test cases

### ISSUE THREAD

**Issue by zhbancheva** [janito84/naturalmilk#15]
For **Test Plan** to create part **Test cases**.
To cover the following points:

Test case ID: 
Test priority (Low/Medium/High):
Module Name – 
Test Executed By: 
Test Execution Date: 
Test Title/Name: 
Test Summary/Description: .
Pre-condition: 
Test Steps: 
1.  Press ......
2.  Standard Open screen is displayed.
3.  User chooses ........
4.  Press ...... button
Test Data: Source_01
Expected Result:  
Actual result: 
Status (Pass/Fail): 
Defect ID/Link: https://github.com/.......................

For example see  file _example_Test_plan_ or other files.

**Comment by softunigroupproject** [comment]
[Test Cases.xlsx](https://github.com/janito84/naturalmilk/files/225904/Test.Cases.xlsx)

**Comment by softunigroupproject** [comment]
Revision not final
[Test Cases.xlsx](https://github.com/janito84/naturalmilk/files/227480/Test.Cases.xlsx)

**Comment by softunigroupproject** [comment]
Final - Done!
[Test Cases.xlsx](https://github.com/janito84/naturalmilk/files/229827/Test.Cases.xlsx)
