### ISSUE TITLE
SRS:Product functions

### ISSUE THREAD

**Issue by zhbancheva** [janito84/naturalmilk#2]
For SRS to create part **Product functions**
To cover the following points:Enables effective contact management, Offers a single, uniform view of customer information etc.

For example see _2.1 Product perspective_ and _2.2 Product functions_ from file _QA-FundamentalsSRS-Example-Team_Provers_v2_  or other files.

**Comment by softunigroupproject** [comment]
Boby I wrote the Product perspective as we already talked about that. I will upload it tomorrow. You can do the other ones. Thanks.

**Comment by zhbancheva** [comment]
**Petra** has done that part.
