### ISSUE TITLE
SRS: Functional Requirements: Use cases 2

### ISSUE THREAD

**Issue by zhbancheva** [janito84/naturalmilk#4]
To create Functional Requirements:

> Bobi
> - Descriptions of data to be entered into the web site
> - Descriptions of operations performed by each screen
> - Descriptions of work-flows performed by the screens
> - Descriptions of system reports or other outputs
> - Who can enter the data into the system
> - How the system meets applicable regulatory requirements
> - information about particular product, such as product number, item, name, category, images of products, description, features, constraints of products, which are to be displayed on the website.
> - information about the products and services
> - discounts applicable for the particular product of a vendor/seller
> - Transactions: All transactions undergoing in the website will be controlled and managed by this module. Transactions in the sense, Shopping Cart management.
> - Reporting: This module deals with report management of the entire system. This includes three sub-modules Stock Report, Order Report and Delivery Report.
> - Order Report: Order Report will have the list of products ordered and the customer details who have bought that product, which are undelivered.
> - Delivery Report: Delivery Reports will generate products list, which are delivered to customers.

---

We have to divide the following main points:
- Use cases related to system authorization  - **I started doing**
- Use cases related to buy - **I started doing**
- Use cases related to information display
- Use cases related to Administration modul / Use cases related to securitie

> Desi please write if I missed something about the main points

**Comment by softunigroupproject** [comment]
Use cases related to search function - Allows users to search for products

**Comment by DessLazaro** [comment]
1. File with draft Admin use cases is uploaded.
2. File with draft Functional Requirements is uploaded.
3. File with Search use case is uploaded.
   @janito84 @softunigroupproject @bobosam @iboby @georgipyrvanov  Please comment in order to finalize.

**Comment by DessLazaro** [comment]
@softunigroupproject Petra, I have uploaded one use case regarding the search function.
Comments are very welcome.

**Comment by DessLazaro** [comment]
@janito84 Jani, as we have already discussed the Security part is included in the non-functional requirements. :)

**Comment by DessLazaro** [comment]
Completed.
