### ISSUE TITLE
SRS: User Screens

### ISSUE THREAD

**Issue by zhbancheva** [janito84/naturalmilk#6]
To create for SRS part **User Screens**
pictures for : Sign in, User Shopping bag, Administration etc.

For example file _QA-FundamentalsSRS-Example-Team_Provers_v2_ points or other files.

**Comment by bobosam** [comment]
all screens are ready

**Comment by zhbancheva** [comment]
good :) but picture SignOut.PNG  contained picture for sign in. Missing picture for Sign OUT.
Please correct it.

**Comment by bobosam** [comment]
This picture SignOut.png  shows what happens when we click "Sign Out" button.
